---
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: pr0d1r2/nix-lefthook-ci-action@e5076886865ac3aed148127ea3aa7269ffcf6989
        with:
          skip-build: true
