---
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: pr0d1r2/nix-lefthook-ci-action@ce9a118b05e90e186dba48a82067adeed185f7d4
        with:
          skip-build: true
          keep-home: true
          extra-env: "HOME=${{ env.HOME }}"
        env:
          LEFTHOOK_EXCLUDE: changelog-touched
